export CUDA_VISIBLE_DEVICES=0

model_name=PatchTST

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_12 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 12 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 32 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --lradj TST \
  --train_epochs 100 \
  --patience 10 \
  --use_norm 1 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_24 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 24 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 32 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --lradj TST \
  --train_epochs 100 \
  --patience 10 \
  --use_norm 1 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_48 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 48 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 32 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --lradj TST \
  --train_epochs 100 \
  --patience 10 \
  --use_norm 1 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS08.npz \
  --model_id PEMS08_96_96 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 170 \
  --dec_in 170 \
  --c_out 170 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 32 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --lradj TST \
  --train_epochs 100 \
  --patience 10 \
  --use_norm 0 \
  --itr 1