export CUDA_VISIBLE_DEVICES=0

model_name=PatchTST

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 128 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --train_epochs 100 \
  --patience 20 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 128 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --train_epochs 100 \
  --patience 20 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 128 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --train_epochs 100 \
  --patience 20 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/weather/ \
  --data_path weather.csv \
  --model_id Weather_96_96 \
  --model $model_name \
  --data custom \
  --features M \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 3 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 21 \
  --dec_in 21 \
  --c_out 21 \
  --des 'Exp' \
  --d_model 128 \
  --d_ff 256 \
  --dropout 0.2 \
  --n_heads 16 \
  --batch_size 128 \
  --pct_start 0.2 \
  --learning_rate 0.0001 \
  --train_epochs 100 \
  --patience 20 \
  --itr 1